/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutUsesRouteImport } from './routes/about/uses'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'
import { Route as AdminVisitorsIndexRouteImport } from './routes/admin/visitors/index'
import { Route as AdminUsesIndexRouteImport } from './routes/admin/uses/index'
import { Route as AdminTechnologiesIndexRouteImport } from './routes/admin/technologies/index'
import { Route as AdminSocialLinksIndexRouteImport } from './routes/admin/social-links/index'
import { Route as AdminSkillsIndexRouteImport } from './routes/admin/skills/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSeriesIndexRouteImport } from './routes/admin/series/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminGuestBookIndexRouteImport } from './routes/admin/guest-book/index'
import { Route as AdminExperienceIndexRouteImport } from './routes/admin/experience/index'
import { Route as AdminEducationIndexRouteImport } from './routes/admin/education/index'
import { Route as AdminContactSubmissionsIndexRouteImport } from './routes/admin/contact-submissions/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as BlogSeriesSlugIndexRouteImport } from './routes/blog/series/$slug/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsesRoute = AboutUsesRouteImport.update({
  id: '/about/uses',
  path: '/about/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitorsIndexRoute = AdminVisitorsIndexRouteImport.update({
  id: '/visitors/',
  path: '/visitors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsesIndexRoute = AdminUsesIndexRouteImport.update({
  id: '/uses/',
  path: '/uses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTechnologiesIndexRoute = AdminTechnologiesIndexRouteImport.update({
  id: '/technologies/',
  path: '/technologies/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialLinksIndexRoute = AdminSocialLinksIndexRouteImport.update({
  id: '/social-links/',
  path: '/social-links/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsIndexRoute = AdminSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesIndexRoute = AdminSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestBookIndexRoute = AdminGuestBookIndexRouteImport.update({
  id: '/guest-book/',
  path: '/guest-book/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperienceIndexRoute = AdminExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationIndexRoute = AdminEducationIndexRouteImport.update({
  id: '/education/',
  path: '/education/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactSubmissionsIndexRoute =
  AdminContactSubmissionsIndexRouteImport.update({
    id: '/contact-submissions/',
    path: '/contact-submissions/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSeriesSlugIndexRoute = BlogSeriesSlugIndexRouteImport.update({
  id: '/blog/series/$slug/',
  path: '/blog/series/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about/uses': typeof AboutUsesRoute
  '/about': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsIndexRoute
  '/admin/education': typeof AdminEducationIndexRoute
  '/admin/experience': typeof AdminExperienceIndexRoute
  '/admin/guest-book': typeof AdminGuestBookIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/series': typeof AdminSeriesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/skills': typeof AdminSkillsIndexRoute
  '/admin/social-links': typeof AdminSocialLinksIndexRoute
  '/admin/technologies': typeof AdminTechnologiesIndexRoute
  '/admin/uses': typeof AdminUsesIndexRoute
  '/admin/visitors': typeof AdminVisitorsIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/blog/series/$slug': typeof BlogSeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/uses': typeof AboutUsesRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/contact-submissions': typeof AdminContactSubmissionsIndexRoute
  '/admin/education': typeof AdminEducationIndexRoute
  '/admin/experience': typeof AdminExperienceIndexRoute
  '/admin/guest-book': typeof AdminGuestBookIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/series': typeof AdminSeriesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/skills': typeof AdminSkillsIndexRoute
  '/admin/social-links': typeof AdminSocialLinksIndexRoute
  '/admin/technologies': typeof AdminTechnologiesIndexRoute
  '/admin/uses': typeof AdminUsesIndexRoute
  '/admin/visitors': typeof AdminVisitorsIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/blog/series/$slug': typeof BlogSeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about/uses': typeof AboutUsesRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/contact-submissions/': typeof AdminContactSubmissionsIndexRoute
  '/admin/education/': typeof AdminEducationIndexRoute
  '/admin/experience/': typeof AdminExperienceIndexRoute
  '/admin/guest-book/': typeof AdminGuestBookIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/series/': typeof AdminSeriesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/skills/': typeof AdminSkillsIndexRoute
  '/admin/social-links/': typeof AdminSocialLinksIndexRoute
  '/admin/technologies/': typeof AdminTechnologiesIndexRoute
  '/admin/uses/': typeof AdminUsesIndexRoute
  '/admin/visitors/': typeof AdminVisitorsIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/blog/series/$slug/': typeof BlogSeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about/uses'
    | '/about'
    | '/admin/'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contact-submissions'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/guest-book'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/social-links'
    | '/admin/technologies'
    | '/admin/uses'
    | '/admin/visitors'
    | '/blog/$slug'
    | '/blog/series/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/uses'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contact-submissions'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/guest-book'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/social-links'
    | '/admin/technologies'
    | '/admin/uses'
    | '/admin/visitors'
    | '/blog/$slug'
    | '/blog/series/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about/uses'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/contact/'
    | '/projects/'
    | '/admin/blogs/'
    | '/admin/categories/'
    | '/admin/contact-submissions/'
    | '/admin/education/'
    | '/admin/experience/'
    | '/admin/guest-book/'
    | '/admin/login/'
    | '/admin/profile/'
    | '/admin/projects/'
    | '/admin/series/'
    | '/admin/settings/'
    | '/admin/skills/'
    | '/admin/social-links/'
    | '/admin/technologies/'
    | '/admin/uses/'
    | '/admin/visitors/'
    | '/blog/$slug/'
    | '/blog/series/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutUsesRoute: typeof AboutUsesRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
  BlogSeriesSlugIndexRoute: typeof BlogSeriesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/uses': {
      id: '/about/uses'
      path: '/about/uses'
      fullPath: '/about/uses'
      preLoaderRoute: typeof AboutUsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors/': {
      id: '/admin/visitors/'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uses/': {
      id: '/admin/uses/'
      path: '/uses'
      fullPath: '/admin/uses'
      preLoaderRoute: typeof AdminUsesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/technologies/': {
      id: '/admin/technologies/'
      path: '/technologies'
      fullPath: '/admin/technologies'
      preLoaderRoute: typeof AdminTechnologiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-links/': {
      id: '/admin/social-links/'
      path: '/social-links'
      fullPath: '/admin/social-links'
      preLoaderRoute: typeof AdminSocialLinksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills/': {
      id: '/admin/skills/'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series/': {
      id: '/admin/series/'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AdminSeriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guest-book/': {
      id: '/admin/guest-book/'
      path: '/guest-book'
      fullPath: '/admin/guest-book'
      preLoaderRoute: typeof AdminGuestBookIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experience/': {
      id: '/admin/experience/'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education/': {
      id: '/admin/education/'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-submissions/': {
      id: '/admin/contact-submissions/'
      path: '/contact-submissions'
      fullPath: '/admin/contact-submissions'
      preLoaderRoute: typeof AdminContactSubmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/series/$slug/': {
      id: '/blog/series/$slug/'
      path: '/blog/series/$slug'
      fullPath: '/blog/series/$slug'
      preLoaderRoute: typeof BlogSeriesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminContactSubmissionsIndexRoute: typeof AdminContactSubmissionsIndexRoute
  AdminEducationIndexRoute: typeof AdminEducationIndexRoute
  AdminExperienceIndexRoute: typeof AdminExperienceIndexRoute
  AdminGuestBookIndexRoute: typeof AdminGuestBookIndexRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminSeriesIndexRoute: typeof AdminSeriesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSkillsIndexRoute: typeof AdminSkillsIndexRoute
  AdminSocialLinksIndexRoute: typeof AdminSocialLinksIndexRoute
  AdminTechnologiesIndexRoute: typeof AdminTechnologiesIndexRoute
  AdminUsesIndexRoute: typeof AdminUsesIndexRoute
  AdminVisitorsIndexRoute: typeof AdminVisitorsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminContactSubmissionsIndexRoute: AdminContactSubmissionsIndexRoute,
  AdminEducationIndexRoute: AdminEducationIndexRoute,
  AdminExperienceIndexRoute: AdminExperienceIndexRoute,
  AdminGuestBookIndexRoute: AdminGuestBookIndexRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminSeriesIndexRoute: AdminSeriesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSkillsIndexRoute: AdminSkillsIndexRoute,
  AdminSocialLinksIndexRoute: AdminSocialLinksIndexRoute,
  AdminTechnologiesIndexRoute: AdminTechnologiesIndexRoute,
  AdminUsesIndexRoute: AdminUsesIndexRoute,
  AdminVisitorsIndexRoute: AdminVisitorsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutUsesRoute: AboutUsesRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
  BlogSeriesSlugIndexRoute: BlogSeriesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
